#pragma config(Sensor, in1,    Gyroscope,      sensorGyro)
#pragma config(Motor,  port1,           leftmotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          rightmotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
SensorValue(Gyroscope) = 0;


motor(leftmotor) = 127;
motor(rightmotor) = 127;
wait1Msec(5000);
stopMotor(leftmotor);
stopMotor(rightmotor);


if(SensorValue(Gyroscope)<0){
	motor(rightmotor) = 110;
	motor(leftmotor) = 127;
}
if(SensorValue(Gyroscope)>0){
	motor(leftmotor) = 110;
	motor(rightmotor) = 127;
}
}
