#pragma config(Motor, port2, rightMotor, tmotorNormal, openLoop)
 #pragma config(Motor, port3, leftMotor, tmotorNormal, openLoop, reversed)
 //*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

task main()
 {
 SensorType[in8] = sensorNone;
 wait1Msec(1000);
 SensorType[in8] = sensorGyro;
 wait1Msec(2000);


 motor(leftMotor) = 127;
 motor(rightMotor) = 127;
 int degrees10 = 900;

 while(abs(SensorValue[in8]) < degrees10)
 {

 motor[rightMotor] = 25;
 motor[leftMotor] = -25;
 }

 motor[rightMotor] = -5;
 motor[leftMotor] = 5;
 wait1Msec(250);
 }
