#pragma config(Motor,  port1,           leftmotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while(1==1)
{
	motor(leftmotor) = 63;

}
}
