#pragma config(Sensor, dgtl8,  rightencoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           leftmotor,     tmotorVex393_HBridge, openLoop, encoderPort, dgtl8)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows(DebugStream)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	clearDebugStream();
	clearTimer(T1);
	SensorValue[rightencoder] = 0;

	while(SensorValue[rightencoder] <= 720){
		if(SensorValue[rightencoder] <= 720){
			motor[port1] = 127;
			writeDebugStreamLine("time: %d",time1[T1]);
		}
		else{
			motor[port1] = 0;

			break;
		}

	}


}
